### ISSUE TITLE
Z-order of Pasted Group or Building Block Not Retained

### ISSUE THREAD

**Issue by JackMillerSD** [bancika/diy-layout-creator#388]
When cutting and pasting a group of selected components or when adding a previously saved building block to the canvas the z-order (front-to-back ordering) of the components is not retained.

**Comment by MrYanasak** [comment]
I am having the same or a similar issue - when I "duplicate" a group then try to move that copy...

**Comment by bancika** [comment]
by "duplicate" you mean copy-paste?

**Comment by bancika** [comment]
this should be fixed in one of the recent versions. Please try the latest

**Comment by SlyWink** [comment]
Hello,
The trouble seems to still exist in the latest version (see attached zip)
[bb_test.diy.zip](https://github.com/bancika/diy-layout-creator/files/2922359/bb_test.diy.zip)
