### ISSUE TITLE
Wrong IC pin numbering in Netlist

### ISSUE THREAD

**Issue by mramonlopez** [bancika/diy-layout-creator#703]
When the netlist is generated, the numbering of the pins on the right side of the DIP ICs is reversed

![Captura de Pantalla 2022-05-05 a las 12 49 34](https://user-images.githubusercontent.com/4113158/166909647-d029c81e-dffc-4467-b78f-bc52ba254f8e.png)

![Captura de Pantalla 2022-05-05 a las 12 58 33](https://user-images.githubusercontent.com/4113158/166910044-5af6c2e2-e780-42b7-9237-fc061df53c48.png)

**Comment by bancika** [comment]
fixed for 4.35

**Comment by KinyaKanno** [comment]
I think this bug has not fixed yet. Still remain the same.
I've just downloaded diylc-5.10.0-win64.exe today.
Thanx.
